### ISSUE TITLE
no this module     ngx_stream_pass_module

### ISSUE THREAD

**Issue by spacexnasa** [freenginx/nginx#1]
https://nginx.org/en/CHANGES

Changes with nginx 1.25.5                                        16 Apr 2024

    *) Feature: virtual servers in the stream module.

    *) Feature: the ngx_stream_pass_module.

**Comment by mdounin** [comment]
That's expected: the ngx_stream_pass_module was introduced by F5 in F5 NGINX and was never submitted into freenginx. If you think it worth adding, consider asking F5 developers to submit it. Note though, that I personally very much doubt that such a module needs to be present due to multiple issues it creates.
